SPOTFIRE_CDK_VERSION=4.0.0

# appVersions / images
SPOTFIRE_DEPLOYMENT_VERSION=14.0.9
SPOTFIRE_NETCORE_LANGUAGEPACKS_VERSION=4.0.9
SPOTFIRE_NETCORE_VERSION=4.0.9
SPOTFIRE_NODEMANAGER_VERSION=4.0.9
SPOTFIRE_PYTHONSERVICE_VERSION=4.0.9
SPOTFIRE_RSERVICE_VERSION=4.0.9
SPOTFIRE_SERVER_VERSION=4.0.9
SPOTFIRE_TERRSERVICE_VERSION=4.0.9


